namespace Evaluator
{
    using System.Collections.Generic;

    using Evaluator.AutoGeneratedByGrammar;

    public class EvaluatorListener : EvaluatorBaseListener
    {
        public List<string> Variables { get; set; }

        public EvaluatorListener()
        {
            this.Variables = new List<string>();
        }

        public override void EnterVariable(EvaluatorParser.VariableContext context)
        {
            this.Variables.Add(context.GetText());
            base.EnterVariable(context);
        } 
    }
}