namespace Evaluator
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Antlr4.Runtime;
    using Antlr4.Runtime.Tree;

    using Evaluator.AutoGeneratedByGrammar;

    public class Expression
    {
        private readonly EvaluatorParser parser;
        private readonly IParseTree tree;

        public Expression(string expression)
        {
            this.OriginalExpression = expression;

            this.parser = this.CreateParser(expression);
            var errorListener = this.CreateErrorListener(this.parser);

            this.tree = this.Parse(this.parser, errorListener);

            this.Variables = this.ExtractVariables(this.tree);
        }

        public string OriginalExpression { get; set; }

        public List<string> Variables { get; set; }

        public T Evaluate<T>(Dictionary<string, object> parameters = null)
        {
            var visitor = new EvaluatorVisitor(parameters);

            var actual = visitor.Visit(this.tree);

            if (typeof(T) == typeof(double) || typeof(T) == typeof(bool))
            {
                return (T)actual.value;
            }

            throw new NotSupportedException(string.Format("Can't evaluate for result of type '{0}' !", typeof(T)));
        }

        public string ToStringTree()
        {
            return this.tree.ToStringTree(this.parser);
        }

        private EvaluatorParser CreateParser(string expression)
        {
            var input = new AntlrInputStream(expression);
            var lexer = new EvaluatorLexer(input);
            var tokens = new CommonTokenStream(lexer);
            return new EvaluatorParser(tokens);
        }

        private ThrowingErrorListener CreateErrorListener(EvaluatorParser evaluatorParser)
        {
            var throwingErrorListener = new ThrowingErrorListener();
            evaluatorParser.AddErrorListener(throwingErrorListener);
            return throwingErrorListener;
        }

        private IParseTree Parse(EvaluatorParser evaluatorParser, ThrowingErrorListener throwingErrorListener)
        {
            IParseTree parseTree = evaluatorParser.expr();

            if (throwingErrorListener.Errors.Any())
                throw new ParsingException(string.Join(Environment.NewLine, throwingErrorListener.Errors));

            return parseTree;
        }

        private List<string> ExtractVariables(IParseTree parseTree)
        {
            var evaluatorListener = new EvaluatorListener();
            var walker = new ParseTreeWalker();

            walker.Walk(evaluatorListener, parseTree);

            return evaluatorListener.Variables.ToList();
        }
    }
}